### PR TITLE
Added several fixes to get extension in working condition

### PR DESCRIPTION
**Pull request by romul**
Looks like version in the master branch is completely broken. Added several fixes to work with Spree 1.2.

### CODE REVIEW

**Comment by hybridindie** [comment]
I'm going to pull this in for those wishing to use it but I have a new version - complete rewrite in the v2 branch - it's no where near ready for primetime though. Thanks and expect a much simpler one in the very near future

**Comment by max-krueper** [comment]
I created a fresh project with rails 3.2.9 and spree 1.2.2 and installed spree_sunspot_search as on the website described. I get the following error:
$ rails g sunspot_rails:install
/home/ibaanah/.bundler/ruby/1.9.1/spree_sunspot_search-2d9b668fba76/app/models/product_decorator.rb:7:in `block (2 levels) in <top (required)>': undefined method`fields' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/sunspot-1.3.3/lib/sunspot/util.rb:208:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/sunspot-1.3.3/lib/sunspot/util.rb:208:in`instance_eval_with_context'
...

Is it really working with spree 1.2?

**Comment by romul** [comment]
@muhammad-salafi: Yes, it really works with spree 1.2, but example of initializer (spree_sunspot_search.rb) is outdated. You can fix your local copy of initializer to match changes in this commit: https://github.com/romul/spree_sunspot_search/commit/d375845ab0ab6f7f99d2a5f2a4b0e47574ab7118

**Comment by romul** [comment]
@jbrien I'm generally happy with the current version(although Sunspot namespace would be better to leave), but there's one wish about hits and stored attributes. Wait a pull request. Would be great if you include a similar feature in v2.

**Pull request merged**
